# Generated by Django 3.2.5 on 2021-07-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='print',
            field=models.ImageField(default=None, null=True, upload_to='print/'),
        ),
    ]
