# Generated by Django 3.2.5 on 2021-08-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0002_variation_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='source',
            field=models.IntegerField(choices=[(0, 'Rov1'), (1, 'Rov2'), (2, 'Rov3'), (3, 'Van1'), (4, 'Van2'), (5, 'Van3'), (6, 'And1'), (7, 'And2'), (8, 'And3'), (9, 'Jak1'), (10, 'Jak2'), (11, 'Jak3'), (12, 'Frn1'), (13, 'Frn2'), (14, 'Frn3'), (15, 'Pic1'), (16, 'Pic2'), (17, 'Pic3')]),
        ),
    ]
